### PR TITLE
Add Debian packaging information

### PR DESCRIPTION
**Pull request by mkindahl**
Add the necessary information to build Debian packages from inside the repository. With this commit, you can build packages using

    debmake -t -i debuild

### CODE REVIEW

**Comment by narc-Ontakac2** [comment]
You might want to use native format instead of quilt for now. This removes the need for the source tarball and `-<n>`  in the version number.

The copyright file does not have to contain the apache license. If you can rely on being on a Debian system there already is a copy.

The dh_installdocs in rules can be replaced by a docs file and you might want to include pgxs_debian_control.mk.

**Comment by mkindahl** [comment]
Thanks @narc-Ontakac2!

Not very familiar with the Debian build and release process, so some of these items take longer than I expected. Merging this work for now instead of sitting on it, but will look into these issues separately. 

> You might want to use native format instead of quilt for now. This removes the need for the source tarball and `-<n>` in the version number.

Hmm... building using `debmake -n` does not work unless I do a `debmake -t` first, so will investigate this a little more in a separate PR.

> 
> The copyright file does not have to contain the apache license. If you can rely on being on a Debian system there already is a copy.

Fixed the copyright file, and some others that gave errors.

> 
> The dh_installdocs in rules can be replaced by a docs file and you might want to include pgxs_debian_control.mk.

Included pgx_debian_control.mk, but will look at dh_installdocs separately.

**Comment by narc-Ontakac2** [comment]
> Hmm... building using `debmake -n` does not work unless I do a `debmake -t` first, so will investigate this a little more in a separate PR

I just saw that the debmake man page advises against using native format. I personally find it convenient to use. I will most likely branch my native packages to quilt format when they become official debian packages, but until then there is no need for an additional  -debversion. What I am building _is_ a native package, so native seems appropriate.

A good thing with quilt is however, that you can not accidentally package files that just happen to be in the build directory. Files that are not in the orig.tar or have been modified give an error. If you want that, something like
```
git archive --output=../libsml_${VERSION}.orig.tar.gz --format=tar.gz HEAD
```
might be preferrable over ```debmake -t```.

**Comment by mkindahl** [comment]
> > Hmm... building using `debmake -n` does not work unless I do a `debmake -t` first, so will investigate this a little more in a separate PR
> 
> I just saw that the debmake man page advises against using native format. I personally find it convenient to use. I will most likely branch my native packages to quilt format when they become official debian packages, but until then there is no need for an additional -debversion. What I am building _is_ a native package, so native seems appropriate.

Seems reasonable, yes.
 
> A good thing with quilt is however, that you can not accidentally package files that just happen to be in the build directory. Files that are not in the orig.tar or have been modified give an error. If you want that, something like
> 
> ```
> git archive --output=../libsml_${VERSION}.orig.tar.gz --format=tar.gz HEAD
> ```
> 
> might be preferrable over `debmake -t`.

Yeah, I tried that (that's why there's a `.gitattributes` file in the PR), but it gave other errors.  I'm going to investigate that going forward because that seems way easier than using `debmake -t`.

**Pull request merged**
