### PR TITLE
Debian Packaging 

### PR DESCRIPTION
**Pull request by narc-Ontakac2**
I have turned the current state into a pull request, just in case you want to use it.

Since you seem to be using postgres 13 you need run
```
pg_buildext updatecontrol
```
to change the postgres version and also edit the first line of the changelog. The source patch for postgres 15 is not tested and can surely be improved.

### CODE REVIEW

**Comment by mkindahl** [comment]
Thanks @narc-Ontakac2 ! I'll take a look at it in the next few days.

**Comment by mkindahl** [comment]
Hi @narc-Ontakac2! This looks like it is two contributions:

1. Some fixes to the code to make it build with PG15
2. Starting point for debian packing files.

You might want to submit 1 as a separate PR and we can just merge that. It looks quite straightforward. The other parts would require editing some of the messages. Not sure how you want to approach this. Simplest might be if I create a commit based on this, make the necessary edits, and submit it in both our names.

**Comment by narc-Ontakac2** [comment]
> Simplest might be if I create a commit based on this, make the necessary edits, and submit it in both our names.

Please do that. This is the cleaned up state of what I have been doing up to now and I thought it might be useful.

Concerning part 1 the changes have not yet been tested because when running the tests with 
```
pg_virtualenv make installcheck
```
worker and inval fail. This also happens with -v 13, so it is likely to have a cause in my local system setup.



.

**Comment by mkindahl** [comment]
> > Simplest might be if I create a commit based on this, make the necessary edits, and submit it in both our names.
> 
> Please do that. This is the cleaned up state of what I have been doing up to now and I thought it might be useful.

Ok. Will do.

> Concerning part 1 the changes have not yet been tested because when running the tests with
> 
> ```
> pg_virtualenv make installcheck
> ```
> 
> worker and inval fail. This also happens with -v 13, so it is likely to have a cause in my local system setup.

Hmm.... both of these tests require the UDP port to be available: is the virtual environment messing with access to those in some way? I have problems with that on GitHub and am trying to figure out a solution for that so that the tests can be executed for each pull request.

Also, I have a draft patch #20 for supporting PG15, so not sure if that helps.

**Comment by narc-Ontakac2** [comment]
I have removed my PG15 changes.

The failure of the tests with pg_virtualenv is a mystery to me. It looks like pg_virtualenv is just setting up and starting a postgres cluster without being root. No network related stuff.

**Comment by narc-Ontakac2** [comment]
The failure of the tests with pg_virtualenv is a mystery to me. It looks like pg_virtualenv is just setting up and starting a postgres cluster without being root.

**Comment by narc-Ontakac2** [comment]
As the conflicts show this is mostly obsoleted by #21 by now.

**Comment by mkindahl** [comment]
> As the conflicts show this is mostly obsoleted by #21 by now.

Yes, but I am still working on the workflow and release handling, so will set that up using information from this as template.

**Comment by mkindahl** [comment]
Closing since most of it is applied in #21.

**Pull request closed without merging**
